### ISSUE TITLE
Move from Netlify to Vercel

### ISSUE THREAD

**Issue by kalynbeach** [kalynbeach/kalynbeach-com-astro#5]
Currently the site is deployed and managed on Netlify, but it might be a good idea to move it to Vercel (so it's managed together with my Next.js apps).

## TODOs:
- [x] Add and set up `@astrojs/vercel` adapter
  - [Astro Docs - `@astrojs/vercel`](https://docs.astro.build/en/guides/integrations-guide/vercel/)
  - [Vercel Docs - Astro](https://vercel.com/docs/frameworks/astro)
- [x] Remove Netlify integration/config
  - [x] `astro.config.mjs`
  - [x] `site` url
- [x] Remove `@astrojs/partytown` and Google Analytics integration
  - [x] `Analytics`
  - [x] `BaseHead`
- [x] Take site down in Netlify
- [ ] Update `kalynbeach.com` domain settings
  - [x] Set up domain in Vercel
  - [ ] Update DNS as needed
